### ISSUE TITLE
backend handling - foreman style

### ISSUE THREAD

**Issue by tbranyen** [webapp/webapp#7]
Instead of webapp residing inside your framework installs, have webapp manage your framework.

perhaps something like:

``` yaml
backend -
  process: "node"
  command: "server"
```
